export const API_LABELS = {
  GET_ADMIN_NAME_LOADING: "GET_ADMIN_NAME_LOADING",
  GET_ADMIN_NAME_SUCCESS: "GET_ADMIN_NAME_SUCCESS",
  GET_ADMIN_NAME_ERROR: "GET_ADMIN_NAME_ERROR",

  GET_OFFICES_LOADING: "GET_OFFICES_LOADING",
  GET_OFFICES_SUCCESS: "GET_OFFICES_SUCCESS",
  GET_OFFICES_ERROR: "GET_OFFICES_ERROR",

  GET_OFFICE_SHIFTS_LOADING: "GET_OFFICES_SHIFT_LOADING",
  GET_OFFICE_SHIFTS_SUCCESS: "GET_OFFICES_SHIFT_SUCCESS",
  GET_OFFICE_SHIFTS_ERROR: "GET_OFFICES_SHIFT_ERROR",

};
